from __future__ import annotations

from fastapi import APIRouter

from app.api.handlers import financials as handlers
from app.api.source_contracts import add_user_visible_route
from app.api.schemas.company_charts import (
    CompanyChartsDashboardResponse,
    CompanyChartsForecastAccuracyResponse,
    CompanyChartsShareSnapshotRecordPayload,
    CompanyChartsScenarioDetailPayload,
    CompanyChartsScenarioListResponse,
)
from app.api.schemas.equity_claim_risk import CompanyEquityClaimRiskResponse
from app.api.schemas.financials import (
    CompanyCapitalStructureResponse,
    CompanyChangesSinceLastFilingResponse,
    CompanyCompareResponse,
    CompanyDerivedMetricsResponse,
    CompanyDerivedMetricsSummaryResponse,
    CompanyFactsResponse,
    CompanyFilingInsightsResponse,
    CompanyFinancialsResponse,
    CompanyFinancialRestatementsResponse,
    CompanyMetricsTimeseriesResponse,
    CompanySegmentHistoryResponse,
)


def build_router() -> APIRouter:
    router = APIRouter(tags=["financials"])
    add_user_visible_route(
        router,
        "/api/companies/compare",
        handlers.company_compare,
        methods=["GET"],
        response_model=CompanyCompareResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts",
        handlers.company_charts,
        methods=["GET"],
        response_model=CompanyChartsDashboardResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/what-if",
        handlers.company_charts_what_if,
        methods=["POST"],
        response_model=CompanyChartsDashboardResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/forecast-accuracy",
        handlers.company_charts_forecast_accuracy,
        methods=["GET"],
        response_model=CompanyChartsForecastAccuracyResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/scenarios",
        handlers.company_charts_scenarios,
        methods=["GET"],
        response_model=CompanyChartsScenarioListResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/scenarios",
        handlers.company_charts_scenario_create,
        methods=["POST"],
        response_model=CompanyChartsScenarioDetailPayload,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/scenarios/{scenario_id}",
        handlers.company_charts_scenario_detail,
        methods=["GET"],
        response_model=CompanyChartsScenarioDetailPayload,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/scenarios/{scenario_id}",
        handlers.company_charts_scenario_update,
        methods=["POST"],
        response_model=CompanyChartsScenarioDetailPayload,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/scenarios/{scenario_id}/clone",
        handlers.company_charts_scenario_clone,
        methods=["POST"],
        response_model=CompanyChartsScenarioDetailPayload,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/share-snapshots",
        handlers.company_charts_share_snapshot_create,
        methods=["POST"],
        response_model=CompanyChartsShareSnapshotRecordPayload,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/charts/share-snapshots/{snapshot_id}",
        handlers.company_charts_share_snapshot_detail,
        methods=["GET"],
        response_model=CompanyChartsShareSnapshotRecordPayload,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/financials",
        handlers.company_financials,
        methods=["GET"],
        response_model=CompanyFinancialsResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/segment-history",
        handlers.company_segment_history,
        methods=["GET"],
        response_model=CompanySegmentHistoryResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/capital-structure",
        handlers.company_capital_structure,
        methods=["GET"],
        response_model=CompanyCapitalStructureResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/equity-claim-risk",
        handlers.company_equity_claim_risk,
        methods=["GET"],
        response_model=CompanyEquityClaimRiskResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/filing-insights",
        handlers.company_filing_insights,
        methods=["GET"],
        response_model=CompanyFilingInsightsResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/changes-since-last-filing",
        handlers.company_changes_since_last_filing,
        methods=["GET"],
        response_model=CompanyChangesSinceLastFilingResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/metrics-timeseries",
        handlers.company_metrics_timeseries,
        methods=["GET"],
        response_model=CompanyMetricsTimeseriesResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/metrics",
        handlers.company_derived_metrics,
        methods=["GET"],
        response_model=CompanyDerivedMetricsResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/metrics/summary",
        handlers.company_derived_metrics_summary,
        methods=["GET"],
        response_model=CompanyDerivedMetricsSummaryResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/financial-history",
        handlers.company_financial_history,
        methods=["GET"],
        response_model=CompanyFactsResponse,
    )
    add_user_visible_route(
        router,
        "/api/companies/{ticker}/financial-restatements",
        handlers.company_financial_restatements,
        methods=["GET"],
        response_model=CompanyFinancialRestatementsResponse,
    )
    return router
