import type { InvestmentMemoInput } from "@/lib/investment-memo";

export const investmentMemoFixture = {
  ticker: "ACME",
  exportedAt: "2026-05-04T12:00:00.000Z",
  company: {
    ticker: "ACME",
    name: "Acme Corp",
    cik: "0000123456",
    sector: "Technology",
    market_industry: "Software",
    last_checked: "2026-03-10T00:00:00Z",
    cache_state: "fresh",
  },
  asOf: "2025-12-31",
  lastRefreshedAt: "2026-03-10T00:00:00Z",
  provenance: [
    {
      source_id: "sec_companyfacts",
      source_tier: "official_regulator",
      display_label: "SEC Company Facts (XBRL)",
      url: "https://data.sec.gov/api/xbrl/companyfacts/",
      default_freshness_ttl_seconds: 21600,
      disclosure_note: "Official SEC XBRL companyfacts feed normalized into canonical financial statements.",
      role: "primary",
      as_of: "2025-12-31",
      last_refreshed_at: "2026-03-10T00:00:00Z",
    },
  ],
  sourceMix: {
    source_ids: ["sec_companyfacts"],
    source_tiers: ["official_regulator"],
    primary_source_ids: ["sec_companyfacts"],
    fallback_source_ids: [],
    official_only: true,
  },
  filingTimeline: [
    {
      date: "2025-12-31",
      form: "10-K",
      description: "Annual report",
      accession: "0000123456-26-000001",
    },
    {
      date: "2025-09-30",
      form: "10-Q",
      description: "Quarterly report",
      accession: "0000123456-25-000002",
    },
  ],
  latestFinancial: {
    filing_type: "10-K",
    statement_type: "annual",
    period_start: "2025-01-01",
    period_end: "2025-12-31",
    source: "sec_companyfacts",
    last_updated: "2026-03-10T00:00:00Z",
    last_checked: "2026-03-10T00:00:00Z",
    revenue: 6_200_000_000,
    gross_profit: 3_800_000_000,
    operating_income: 1_500_000_000,
    net_income: 1_200_000_000,
    total_assets: 25_000_000_000,
    current_assets: 8_000_000_000,
    total_liabilities: 12_000_000_000,
    current_liabilities: 3_000_000_000,
    retained_earnings: 5_000_000_000,
    sga: 1_000_000_000,
    research_and_development: 800_000_000,
    interest_expense: 150_000_000,
    income_tax_expense: 300_000_000,
    inventory: 500_000_000,
    cash_and_cash_equivalents: 2_000_000_000,
    short_term_investments: 500_000_000,
    cash_and_short_term_investments: 2_500_000_000,
    accounts_receivable: 1_200_000_000,
    accounts_payable: 600_000_000,
    goodwill_and_intangibles: 4_000_000_000,
    current_debt: 200_000_000,
    long_term_debt: 3_500_000_000,
    stockholders_equity: 13_000_000_000,
    lease_liabilities: 400_000_000,
    operating_cash_flow: 2_000_000_000,
    depreciation_and_amortization: 300_000_000,
    capex: 500_000_000,
    acquisitions: null,
    debt_changes: null,
    dividends: 200_000_000,
    share_buybacks: 400_000_000,
    free_cash_flow: 1_500_000_000,
    eps: 3.25,
    shares_outstanding: 400_000_000,
    stock_based_compensation: 120_000_000,
    weighted_average_diluted_shares: 385_000_000,
    segment_breakdown: [
      {
        segment_name: "Core Platform",
        revenue: 4_092_000_000,
        share_of_revenue: 0.661,
      },
      {
        segment_name: "Services",
        revenue: 2_108_000_000,
        share_of_revenue: 0.339,
      },
    ],
    reconciliation: null,
  } as InvestmentMemoInput["latestFinancial"],
  annualStatementsCount: 5,
  topSegment: {
    segment_name: "Core Platform",
    revenue: 4_092_000_000,
    share_of_revenue: 0.661,
  } as InvestmentMemoInput["topSegment"],
  snapshotNarrative:
    "Acme Corp last reported $6.20B of revenue and $1.50B of free cash flow; Core Platform contributes 66.1% of reported revenue; 2 current alerts are already on the monitor.",
  whatChangedNarrative:
    "The latest comparable filing surfaced 3 curated high-signal changes and 0 comment-letter updates.",
  businessQualityNarrative:
    "Revenue is up 8.5% year over year, operating margin sits at 24.2%, free-cash-flow margin at 24.2%, and debt-to-assets at 48.0%.",
  capitalRiskNarrative:
    "Near-term debt due is $200.00M, net dilution is 2.1%, governance coverage spans 3 proxy filings.",
  valuationNarrative:
    "Cached model anchors put intrinsic value about 15.0% above the latest price.",
  monitorNarrative:
    "2 alerts are currently on the monitor for ACME.",
  capitalSignalRows: [
    {
      signal: "Capital markets",
      currentRead: "4 filings · largest offering $500.00M",
      latestEvidence: "Mar 10, 2026",
    },
    {
      signal: "Governance",
      currentRead: "3 proxy filings · 2 with vote items",
      latestEvidence: "Jun 15, 2025",
    },
  ],
  monitorChecklist: [
    {
      title: "Refresh status",
      detail: "No refresh queued. Last full company check ran on Mar 10, 2026.",
    },
    {
      title: "Alert count",
      detail: "0 high, 2 medium, and 0 low alerts are currently active.",
    },
  ],
  changes: {
    current_filing: null,
    previous_filing: null,
    metric_deltas: [],
    new_risk_indicators: [],
    segment_shifts: [],
    share_count_changes: [],
    capital_structure_changes: [],
    amended_prior_values: [],
    high_signal_changes: [],
    comment_letter_history: {
      total_letters: 0,
      letters_since_previous_filing: 0,
      latest_filing_date: null,
      recent_letters: [],
    },
    summary: {
      filing_type: "10-K",
      current_period_start: "2025-01-01",
      current_period_end: "2025-12-31",
      previous_period_start: "2024-01-01",
      previous_period_end: "2024-12-31",
      metric_delta_count: 42,
      new_risk_indicator_count: 1,
      segment_shift_count: 0,
      share_count_change_count: 2,
      capital_structure_change_count: 1,
      amended_prior_value_count: 0,
      high_signal_change_count: 3,
      comment_letter_count: 0,
    },
  } as InvestmentMemoInput["changes"],
  earningsSummary: {
    company: {
      id: 1,
      ticker: "ACME",
      cik: "0000123456",
      name: "Acme Corp",
      sector: "Technology",
      market_sector: "Technology",
      market_industry: "Software",
      last_checked: null,
      cache_state: "fresh",
      strict_official_mode: false,
      last_checked_financials: null,
      last_checked_filings: null,
    },
    summary: {
      latest_revenue: 6_200_000_000,
      latest_diluted_eps: 3.25,
      latest_period_end: "2025-12-31",
      latest_report_date: "2026-02-14",
      period_count: 5,
      has_beats: false,
      beat_count: 0,
      miss_count: 0,
    },
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    error: null,
    provenance: [],
    as_of: "2025-12-31",
    last_refreshed_at: "2026-03-10T00:00:00Z",
    source_mix: null,
    confidence_flags: [],
  } as InvestmentMemoInput["earningsSummary"],
  activityOverview: {
    company: {
      id: 1,
      ticker: "ACME",
      cik: "0000123456",
      name: "Acme Corp",
      sector: "Technology",
      market_sector: "Technology",
      market_industry: "Software",
      last_checked: null,
      cache_state: "fresh",
      strict_official_mode: false,
      last_checked_financials: null,
      last_checked_filings: null,
    },
    summary: { total: 2, high: 0, medium: 2, low: 0 },
    alerts: [
      {
        id: "a1",
        title: "Increased share repurchase program",
        severity: "medium",
        date: "2026-02-14",
        category: "capital_structure",
        description: null,
      },
    ],
    entries: [
      {
        id: "e1",
        title: "10-K filed",
        date: "2026-02-14",
        type: "filing",
        severity: "low",
        description: null,
        source_id: "sec_companyfacts",
      },
    ],
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    error: null,
    provenance: [],
    as_of: "2025-12-31",
    last_refreshed_at: "2026-03-10T00:00:00Z",
    source_mix: null,
    confidence_flags: [],
  } as InvestmentMemoInput["activityOverview"],
  capitalStructure: {
    company: {
      id: 1,
      ticker: "ACME",
      cik: "0000123456",
      name: "Acme Corp",
      sector: "Technology",
      market_sector: "Technology",
      market_industry: "Software",
      last_checked: null,
      cache_state: "fresh",
      strict_official_mode: false,
      last_checked_financials: null,
      last_checked_filings: null,
    },
    latest: {
      period_end: "2025-12-31",
      summary: {
        total_debt: 3_700_000_000,
        net_dilution_ratio: 0.021,
        debt_due_next_twelve_months: 200_000_000,
      },
    },
    history: [],
    last_capital_structure_check: "2026-03-10T00:00:00Z",
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    provenance: [],
    as_of: "2025-12-31",
    last_refreshed_at: "2026-03-10T00:00:00Z",
    source_mix: null,
    confidence_flags: [],
  } as InvestmentMemoInput["capitalStructure"],
  capitalMarketsSummary: {
    company: null,
    summary: {},
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    error: null,
  } as InvestmentMemoInput["capitalMarketsSummary"],
  governanceSummary: {
    company: null,
    summary: {},
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    error: null,
  } as InvestmentMemoInput["governanceSummary"],
  ownershipSummary: {
    company: null,
    summary: {},
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    error: null,
  } as InvestmentMemoInput["ownershipSummary"],
  models: {
    company: null,
    requested_models: ["dcf", "residual_income"],
    models: [
      {
        model_name: "dcf",
        status: "supported",
        result: {
          fair_value_per_share: 146.25,
        },
      },
    ],
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    provenance: [],
    as_of: "2025-12-31",
    last_refreshed_at: "2026-03-10T00:00:00Z",
    source_mix: null,
    confidence_flags: [],
  } as InvestmentMemoInput["models"],
  peers: {
    company: null,
    peer_basis: "sector",
    available_companies: [],
    selected_tickers: ["ACME", "WIDG"],
    notes: [],
    peers: [
      {
        ticker: "ACME",
        name: "Acme Corp",
        pe: 18.4,
        ev_to_ebit: 14.1,
        latest_price: 127.5,
        is_focus: true,
      },
      {
        ticker: "WIDG",
        name: "Widget Systems",
        pe: 21.2,
        ev_to_ebit: 16.3,
        latest_price: 98.1,
        is_focus: false,
      },
    ],
    refresh: { triggered: false, reason: "fresh", ticker: "ACME", job_id: null },
    diagnostics: null,
    provenance: [],
    as_of: "2025-12-31",
    last_refreshed_at: "2026-03-10T00:00:00Z",
    source_mix: null,
    confidence_flags: [],
  } as InvestmentMemoInput["peers"],
} as unknown as InvestmentMemoInput;