export interface MetricGlossaryEntry {
  label: string;
  explanation: string;
  source_note: string;
}

export const METRIC_GLOSSARY: Record<string, MetricGlossaryEntry> = {
  revenue: {
    label: "Revenue",
    explanation: "Revenue measures the sales the company recognized during the period before expenses. Higher is usually better if margins and cash conversion remain healthy.",
    source_note: "Drawn from reported income statements in cached SEC filings.",
  },
  gross_profit: {
    label: "Gross Profit",
    explanation: "Gross profit is revenue minus the direct cost of producing goods or services. It shows how much economic room the business has before overhead and financing costs.",
    source_note: "Derived from reported revenue and cost of goods sold in SEC filings.",
  },
  operating_income: {
    label: "Operating Income",
    explanation: "Operating income measures profit from the core business before interest and taxes. It is a cleaner view of operating performance than net income alone.",
    source_note: "Taken from the operating section of reported income statements.",
  },
  net_income: {
    label: "Net Income",
    explanation: "Net income is profit after operating costs, interest, taxes, and other non-operating items. It is useful, but can be distorted by one-time gains or charges.",
    source_note: "Taken from the bottom-line profit reported in SEC filings.",
  },
  eps: {
    label: "EPS",
    explanation: "Earnings per share shows how much profit is attributable to each diluted share outstanding. Higher is better, but buybacks and dilution can move EPS independently of business quality.",
    source_note: "Uses diluted EPS when available from reported filings.",
  },
  operating_cash_flow: {
    label: "Operating Cash Flow",
    explanation: "Operating cash flow shows the cash generated by normal operations before capital spending. It helps separate accounting profit from actual cash generation.",
    source_note: "Taken from reported cash-flow statements in SEC filings.",
  },
  free_cash_flow: {
    label: "Free Cash Flow",
    explanation: "Free cash flow is operating cash flow minus capital expenditures. It is the cash left to pay debt, repurchase shares, pay dividends, or reinvest elsewhere.",
    source_note: "Calculated from reported operating cash flow and capex in SEC filings.",
  },
  total_assets: {
    label: "Total Assets",
    explanation: "Total assets represent everything the company controls that has economic value. They provide the capital base used for returns, leverage, and turnover ratios.",
    source_note: "Taken from reported balance sheets.",
  },
  total_liabilities: {
    label: "Total Liabilities",
    explanation: "Total liabilities capture the company’s obligations to creditors and other claimants. Rising liabilities are not automatically bad, but they increase financial claims ahead of equity.",
    source_note: "Taken from reported balance sheets.",
  },
  shares_outstanding: {
    label: "Shares Outstanding",
    explanation: "Shares outstanding represent the diluted ownership claims on the business. Lower or stable share counts generally help each share capture more of the company’s economics.",
    source_note: "Taken from diluted share counts or equity disclosures in SEC filings.",
  },
  stock_based_compensation: {
    label: "Stock-Based Comp",
    explanation: "Stock-based compensation is equity paid to employees and executives instead of cash. It can preserve short-term cash while diluting existing shareholders over time.",
    source_note: "Taken from reported compensation expense in SEC filings.",
  },
  current_ratio: {
    label: "Current Ratio",
    explanation: "Current ratio compares short-term assets with short-term liabilities. Higher is generally safer because it suggests the company can cover near-term obligations more easily.",
    source_note: "Calculated from reported current assets and current liabilities.",
  },
  cash_ratio: {
    label: "Cash Ratio",
    explanation: "Cash ratio compares cash and near-cash assets with short-term liabilities. It is a stricter liquidity test than the current ratio because inventory and receivables are excluded.",
    source_note: "Calculated from cash balances and current liabilities in reported filings.",
  },
  debt_to_assets: {
    label: "Debt / Assets",
    explanation: "Debt to assets measures how much of the balance sheet is financed by liabilities. Lower is usually safer because less of the asset base is spoken for by creditors.",
    source_note: "Calculated from reported liabilities and total assets.",
  },
  debt_to_equity: {
    label: "Debt / Equity",
    explanation: "Debt to equity compares creditor financing with the equity cushion beneath it. Lower is generally safer because it leaves more loss-absorbing capital ahead of insolvency risk.",
    source_note: "Calculated from reported liabilities and equity, or derived from related balance-sheet ratios when needed.",
  },
  revenue_growth: {
    label: "Revenue Growth",
    explanation: "Revenue growth measures how quickly sales are increasing versus the prior period. Higher is better when growth is durable and not bought with collapsing margins.",
    source_note: "Calculated from reported filing history or the derived metrics mart.",
  },
  eps_growth: {
    label: "EPS Growth",
    explanation: "EPS growth measures how quickly earnings per diluted share are improving versus the prior period. Strong EPS growth is more convincing when it comes from better operations rather than shrinking share counts alone.",
    source_note: "Calculated from reported diluted EPS history.",
  },
  gross_margin: {
    label: "Gross Margin",
    explanation: "Gross margin shows gross profit as a share of revenue. Higher margins usually indicate stronger pricing power, better unit economics, or a more favorable business mix.",
    source_note: "Calculated from reported revenue and gross profit.",
  },
  operating_margin: {
    label: "Operating Margin",
    explanation: "Operating margin shows operating income as a share of revenue. Higher is better because more of each sales dollar survives after core operating costs.",
    source_note: "Calculated from reported operating income and revenue.",
  },
  net_margin: {
    label: "Net Margin",
    explanation: "Net margin shows net income as a share of revenue. It captures the final profitability left for shareholders after all expenses and taxes.",
    source_note: "Calculated from reported net income and revenue.",
  },
  fcf_margin: {
    label: "FCF Margin",
    explanation: "Free-cash-flow margin shows how much of revenue turns into free cash flow. Higher is better because it means sales are translating into usable cash rather than just accounting profits.",
    source_note: "Calculated from free cash flow and revenue in the filing history.",
  },
  roa: {
    label: "ROA",
    explanation: "Return on assets measures how efficiently the company turns its asset base into profit. Higher is better because it suggests better use of the resources on the balance sheet.",
    source_note: "Calculated from net income and total assets.",
  },
  roe: {
    label: "ROE",
    explanation: "Return on equity measures how much profit the company generates for common shareholders relative to book equity. Higher is better, but very high ROE can be inflated by heavy leverage or buybacks.",
    source_note: "Calculated from net income and stockholders’ equity.",
  },
  roic_proxy: {
    label: "ROIC",
    explanation: "Return on invested capital measures how efficiently the company uses its debt and equity to generate profits. Higher is better because it suggests the business can reinvest at attractive rates.",
    source_note: "Derived from filing-based profit and invested-capital proxies when direct inputs are incomplete.",
  },
  roic: {
    label: "ROIC",
    explanation: "Return on invested capital measures how efficiently the company uses its debt and equity to generate profits. Higher is better because it suggests the business can reinvest at attractive rates.",
    source_note: "Computed by the model engine from filing-based operating results and invested capital inputs.",
  },
  shareholder_yield: {
    label: "Shareholder Yield",
    explanation: "Shareholder yield combines dividends and net buybacks relative to market value. Higher is better when the business is not stretching the balance sheet to fund payouts.",
    source_note: "Derived from filing-based capital returns and labeled price inputs when necessary.",
  },
  share_dilution: {
    label: "Share Dilution",
    explanation: "Share dilution measures how quickly the share count is expanding over time. Lower is better because each share keeps a larger claim on the business.",
    source_note: "Calculated from reported diluted share counts in filing history.",
  },
  buyback_yield: {
    label: "Buyback Yield",
    explanation: "Buyback yield measures net repurchases relative to the company’s market value. Higher is better when repurchases are funded from real free cash flow and not offset by new issuance.",
    source_note: "Derived from filing-based share repurchases and labeled price inputs.",
  },
  dividend_yield: {
    label: "Dividend Yield",
    explanation: "Dividend yield shows annual dividends relative to the company’s market value. A higher yield can be attractive, but only if the payout is covered by cash generation.",
    source_note: "Derived from reported dividends and labeled market-value inputs.",
  },
  sbc_burden: {
    label: "SBC Burden",
    explanation: "SBC burden measures stock-based compensation relative to revenue or another operating base. Lower is better because less of the economic value is being shifted from shareholders to employees.",
    source_note: "Derived from reported stock-based compensation in SEC filings.",
  },
  leverage_ratio: {
    label: "Leverage Ratio",
    explanation: "Leverage ratio measures how much debt or liabilities the company carries relative to its capital or earnings base. Lower is usually safer because the business has more room to absorb stress.",
    source_note: "Derived from filing-based balance-sheet inputs in the metrics mart.",
  },
  cash_conversion: {
    label: "Cash Conversion",
    explanation: "Cash conversion measures how effectively accounting earnings turn into cash flow. Higher is better because it suggests reported profits are backed by real cash generation.",
    source_note: "Derived from filing-based earnings and operating cash-flow inputs.",
  },
  cash_conversion_cycle_days: {
    label: "Cash Conversion Cycle",
    explanation: "Cash conversion cycle estimates how many days cash is tied up between paying suppliers and collecting from customers. Lower is generally better because capital comes back faster.",
    source_note: "Derived from inventory, receivables, payables, and revenue or cost inputs from filings.",
  },
  working_capital_days: {
    label: "Working Capital Days",
    explanation: "Working capital days estimate how long working capital is tied up relative to revenue. Lower is generally better because the business needs less capital to support the same sales base.",
    source_note: "Derived from filing-based working capital and revenue inputs.",
  },
  accrual_ratio: {
    label: "Accrual Ratio",
    explanation: "Accrual ratio compares earnings with underlying cash generation. Lower is usually better because less of reported profit depends on accrual accounting rather than cash.",
    source_note: "Derived from reported earnings, cash flow, and balance-sheet movements.",
  },
  segment_concentration: {
    label: "Segment Concentration",
    explanation: "Segment concentration measures how dependent the company is on one line of business or one customer-facing segment. Lower is generally safer because revenue is less concentrated in a single engine.",
    source_note: "Derived from reported segment disclosures in SEC filings.",
  },
  piotroski_score: {
    label: "Piotroski F-Score",
    explanation: "Piotroski F-Score is a 9-point checklist of profitability, leverage, liquidity, and operating-improvement signals. Higher is better because more of the balance-sheet and earnings tests are passing.",
    source_note: "Computed by the model engine from annual filing history; partial filings can reduce score coverage.",
  },
  altman_z_score: {
    label: "Altman Z-Score",
    explanation: "Altman Z-Score is a balance-sheet distress proxy that combines profitability, leverage, liquidity, and turnover factors. Higher is generally safer, though it is less reliable for banks, insurers, and some asset-light issuers.",
    source_note: "Computed by the model engine from filing-based balance-sheet and income-statement inputs.",
  },
  filing_lag_days: {
    label: "Filing Lag",
    explanation: "Filing lag measures the delay between the reported period end and the filing date. Lower is better because fresher reporting leaves less time for investors to operate on stale data.",
    source_note: "Derived from SEC filing dates and reported period-end dates.",
  },
  restatement_count: {
    label: "Restatement Count",
    explanation: "Restatement count measures how many historical periods were later amended or revised. Lower is better because repeated restatements can signal weak controls or unstable reporting quality.",
    source_note: "Built from detected amended filings and companyfacts revisions in SEC data.",
  },
  stale_period_flag: {
    label: "Stale Period Flag",
    explanation: "Stale period flag marks rows where the latest cached reporting period is older than expected. A clean value is better because the operating read is based on more current filings.",
    source_note: "Derived from freshness checks on cached filing history.",
  },
  restatement_flag: {
    label: "Restatement Flag",
    explanation: "Restatement flag marks whether the latest screened period has known restatement activity. A clean value is better because the latest operating view is less likely to be revised.",
    source_note: "Derived from the financial restatement detection pipeline.",
  },
  fair_value_gap: {
    label: "Fair Value Gap",
    explanation: "Fair value gap compares the model-derived fair value with the latest price. A larger positive gap suggests more upside, while a negative gap suggests the stock may already be pricing in optimistic assumptions.",
    source_note: "Derived from cached valuation models and the latest labeled price input.",
  },
  implied_growth: {
    label: "Implied Growth",
    explanation: "Implied growth estimates the growth rate already embedded in the current market price. Lower implied growth leaves more room for upside surprise if the business performs better than expected.",
    source_note: "Computed by the reverse-DCF model from current price and filing-based cash-flow inputs.",
  },
  net_interest_margin: {
    label: "Net Interest Margin",
    explanation: "Net interest margin measures the spread between what a bank earns on assets and what it pays on funding. Higher is better because the balance sheet is earning more on each dollar of assets.",
    source_note: "Taken from regulatory bank reporting or derived from bank-interest income disclosures.",
  },
  provision_burden: {
    label: "Provision Burden",
    explanation: "Provision burden measures credit-loss provisioning relative to earnings or revenue capacity. Lower is generally better because less of current income is being absorbed by credit deterioration.",
    source_note: "Derived from bank regulatory filings or bank-specific line items.",
  },
  asset_quality_ratio: {
    label: "Asset Quality",
    explanation: "Asset quality ratio measures how much of the balance sheet is showing credit stress, such as nonperforming assets. Lower is better because fewer loans or assets appear impaired.",
    source_note: "Derived from bank regulatory disclosures.",
  },
  cet1_ratio: {
    label: "CET1 Ratio",
    explanation: "CET1 ratio measures core common equity capital relative to risk-weighted assets. Higher is better because the bank has a larger capital buffer against losses.",
    source_note: "Taken from regulatory capital disclosures.",
  },
  tier1_capital_ratio: {
    label: "Tier 1 Capital Ratio",
    explanation: "Tier 1 capital ratio measures high-quality capital relative to risk-weighted assets. Higher is better because the institution has more loss-absorbing capital.",
    source_note: "Taken from regulatory capital disclosures.",
  },
  total_capital_ratio: {
    label: "Total Capital Ratio",
    explanation: "Total capital ratio measures total qualifying regulatory capital relative to risk-weighted assets. Higher is better because the institution has more capital support for its risk profile.",
    source_note: "Taken from regulatory capital disclosures.",
  },
  core_deposit_ratio: {
    label: "Core Deposit Ratio",
    explanation: "Core deposit ratio measures how much funding comes from stickier deposit sources. Higher is generally better because the funding base is usually cheaper and more stable.",
    source_note: "Derived from reported deposit mix in bank regulatory filings.",
  },
  uninsured_deposit_ratio: {
    label: "Uninsured Deposit Ratio",
    explanation: "Uninsured deposit ratio measures the share of deposits that exceed insurance limits. Lower is generally safer because these deposits can be more flight-prone in a stress scenario.",
    source_note: "Derived from reported uninsured-deposit disclosures in bank filings.",
  },
  tangible_book_value_per_share: {
    label: "Tangible Book / Share",
    explanation: "Tangible book value per share measures net tangible equity per share after removing goodwill and other intangibles. Higher is better because it represents a stronger hard-equity cushion per share.",
    source_note: "Derived from balance-sheet equity and intangible-asset disclosures.",
  },
  roatce: {
    label: "ROATCE",
    explanation: "Return on average tangible common equity measures profitability against tangible common equity rather than total book equity. Higher is better because the bank is earning more on its tangible capital base.",
    source_note: "Derived from bank earnings and tangible-equity inputs.",
  },
};

const METRIC_ALIASES: Record<string, string> = {
  "reported score": "piotroski_score",
  "available signals": "piotroski_score",
  "comparison score": "piotroski_score",
  "piotroski": "piotroski_score",
  "piotroski f score": "piotroski_score",
  "piotroski f-score": "piotroski_score",
  "altman proxy": "altman_z_score",
  "altman z": "altman_z_score",
  "altman z score": "altman_z_score",
  "altman z-score": "altman_z_score",
  "roic proxy": "roic_proxy",
  "roic": "roic",
  "fcf margin": "fcf_margin",
  "free cash flow": "free_cash_flow",
  "operating cash flow": "operating_cash_flow",
  "gross margin": "gross_margin",
  "operating margin": "operating_margin",
  "net margin": "net_margin",
  "return on equity": "roe",
  "return on assets": "roa",
  "debt assets": "debt_to_assets",
  "debt / assets": "debt_to_assets",
  "debt equity": "debt_to_equity",
  "debt / equity": "debt_to_equity",
  "share dilution": "share_dilution",
  "buyback yield": "buyback_yield",
  "dividend yield": "dividend_yield",
  "cash conversion cycle": "cash_conversion_cycle_days",
  "cash conversion cycle days": "cash_conversion_cycle_days",
  "cash conversion": "cash_conversion",
  "working capital days": "working_capital_days",
  "accrual ratio": "accrual_ratio",
  "segment concentration": "segment_concentration",
  "shareholder yield": "shareholder_yield",
  "filing lag": "filing_lag_days",
  "filing lag days": "filing_lag_days",
  "restatement count": "restatement_count",
  "stale period flag": "stale_period_flag",
  "restatement flag": "restatement_flag",
  "net interest income": "revenue",
  "net interest margin": "net_interest_margin",
  "provision burden": "provision_burden",
  "asset quality": "asset_quality_ratio",
  "asset quality ratio": "asset_quality_ratio",
  "cet1": "cet1_ratio",
  "cet1 ratio": "cet1_ratio",
  "tier 1 capital ratio": "tier1_capital_ratio",
  "total capital": "total_capital_ratio",
  "total capital ratio": "total_capital_ratio",
  "core deposit mix": "core_deposit_ratio",
  "core deposit ratio": "core_deposit_ratio",
  "uninsured mix": "uninsured_deposit_ratio",
  "uninsured deposit ratio": "uninsured_deposit_ratio",
  "tangible book / share": "tangible_book_value_per_share",
  "roatce": "roatce",
  "fair value gap": "fair_value_gap",
  "implied growth": "implied_growth",
};

function normalizeMetricToken(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[%/().:+-]+/g, " ")
    .replace(/[_•]+/g, " ")
    .replace(/\s+/g, " ");
}

export function resolveMetricGlossary(metricKey?: string | null, label?: string | null): MetricGlossaryEntry | null {
  const candidates = [metricKey, label]
    .filter((value): value is string => Boolean(value))
    .map((value) => normalizeMetricToken(value));

  for (const candidate of candidates) {
    const directKey = candidate.replace(/\s+/g, "_");
    if (METRIC_GLOSSARY[directKey]) {
      return METRIC_GLOSSARY[directKey];
    }
    const aliasKey = METRIC_ALIASES[candidate];
    if (aliasKey && METRIC_GLOSSARY[aliasKey]) {
      return METRIC_GLOSSARY[aliasKey];
    }
  }

  return null;
}

export function buildMetricTooltip(metricKey?: string | null, label?: string | null): string | null {
  const entry = resolveMetricGlossary(metricKey, label);
  if (!entry) {
    return null;
  }
  return `${entry.label}\n\n${entry.explanation}\n\nSource: ${entry.source_note}`;
}